### PR TITLE
Gradle sync fixes

### PR DESCRIPTION
**Pull request by DevhareSandeep**
Sync fix

### CODE REVIEW

**Review by DevhareSandeep — COMMENTED** [review]
Changes are correct

**Review by Virajjage09 — APPROVED** [review]

**Review by Virajjage09 — APPROVED** [review]

**Comment by Virajjage09** [comment]
approved

**Review by Virajjage09 — APPROVED** [review]
approved

**Review by DevhareSandeep — COMMENTED** [review]
done

**Pull request closed without merging**
